steps:
- uses: actions/first-interaction@v1
  with:
    repo-token: ${{ secrets.GITHUB_TOKEN }}
    issue-message: |-
      # Message with markdown.
      
      This is the message that will be displayed on users' first issue.
