on:
  workflow_dispatch:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> $GITHUB_OUTPUT

  job2:
    needs: job1
    runs-on: ubuntu-latest
    if: ${{ needs.job1.outputs.output1 == 'hello' }}
    steps:
      - run: echo "The output from job1 was 'hello'"

  job3:
    needs: job1
    runs-on: ubuntu-latest
    if: ${{ needs.job1.outputs.output1 == 'not-hello' }}
    steps:
      - run: echo "The output from job1 was not hello
