on:
  workflow_dispatch:

jobs:
  script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        id: script-demo
        with:
          script: |
            const {repo, owner} = github.context.issue;
            const details = await octokit.rest.repos.get({owner, repo});
            console.log(details);
            console.log(details.description);
            return details;
      - name: Show result
        env:
          INFO: ${{ steps.script-demo.outputs.result }}
        run: echo $INFO
