on: push

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Show built-in curl version
        run: curl --version
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Download and compile curl
        run: |-
          pwd
          mkdir curl-binary
          cd curl-binary
          wget https://curl.haxx.se/download/curl-7.69.1.tar.gz
          tar xzvf curl-7.69.1.tar.gz
          cd curl-7.69.1
          ./configure --disable-shared --prefix=/home/runner/work/playing-with-actions/playing-with-actions/curl-binary
          make
          find .
          echo "New curl built:"
          ./src/curl --version
          # Commit the binary to git
          mv ./src/curl /home/runner/work/playing-with-actions/playing-with-actions
          cd /home/runner/work/playing-with-actions/playing-with-actions
          ls -lah
          git add -A curl
          git config user.name "Actions"
          git config user.email "actions@users.noreply.github.com"
          git commit -m "Committing curl binary" || exit 0
          git push
