on: push

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Show built-in curl version
        run: curl --version
      - uses: actions/cache@v1
        id: cache
        with:
          path: /home/runner/work/playing-with-actions/playing-with-actions/curl-binary
          key: ${{ runner.os }}-curl-binary
      - name: Download and compile curl
        if: steps.cache.outputs.cache-hit != 'true'
        run: |-
          mkdir /home/runner/work/playing-with-actions/playing-with-actions/curl-binary
          cd /home/runner/work/playing-with-actions/playing-with-actions/curl-binary
          wget https://curl.haxx.se/download/curl-7.69.1.tar.gz
          tar xzvf curl-7.69.1.tar.gz
          cd curl-7.69.1
          ./configure --prefix=/home/runner/work/playing-with-actions/playing-with-actions/curl-binary
          make
          ls

          
