on:
  push

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: |
          if [ "${{ github.ref }}" == "refs/heads/staging" ]; then
            echo "CONTINUE=true" >> $GITHUB_ENV
          else
            echo "CONTINUE=false" >> $GITHUB_ENV
          fi

  example-job:
    runs-on: ubuntu-latest
    needs: check-branch
    if: env.CONTINUE == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run your tasks
        run: |
          echo "Running tasks on the staging branch."
