name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create zip file
      run: |
        ditto -c -k --keepParent . My.zip
        ls -lah
    - uses: actions/github-script@v4
      name: Upload release attachment
      with:
        script: |
          const path = require('path');
          const fs = require('fs');
          const tag = context.ref.replace("refs/tags/", "");
          // Get release for this tag
          const release = await github.repos.getReleaseByTag({
            context.repo.owner,
            context.repo.repo,
            tag
          });
          // Upload the release asset
          await github.repos.uploadReleaseAsset({
            owner: context.repo.owner,
            repo: context.repo.repo,
            release_id: release.id,
            name: "My.zip",
            data: await fs.readFileSync("My.zip")
          });
